---
- hosts: all
  become: true
  
  tasks:
  - name: create docker image using war file
    command: docker build -t graduation_devops_project:latest .
    args:
      chdir: /opt/docker
   
  - name: create tag to image
    command: docker tag graduation_devops_project mahdibenayed1/graduation_devops_project
    
  - name: push image on to dockerhub
    command: docker push mahdibenayed1/graduation_devops_project
    
  - name: remove docker images from ansible server
    command: docker rmi graduation_devops_project:latest mahdibenayed1/graduation_devops_project
