apiVersion: v1
kind: Service
metadata:
  name: project-service
  labels:
    app: graduation-devops-project
spec:
  selector:
    app: graduation-devops-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
